from sqlalchemy import Column, Integer, String, JSON, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from app.models.base import Base

class TestCase(Base):
    __tablename__ = "test_cases"

    id = Column(Integer, primary_key=True, index=True)
    endpoint_id = Column(Integer, ForeignKey("endpoints.id", ondelete="CASCADE"), nullable=False)
    category = Column(String, nullable=False)  # e.g., "Positive", "Negative", or "Boundary"
    description = Column(String, nullable=False)  # Test case description.
    payload = Column(JSON, nullable=True)  # Request body generated by AI.
    path_params = Column(JSON, nullable=True)  # Values for path parameters.
    query_params = Column(JSON, nullable=True)  # Values for query parameters.
    expected_status = Column(Integer, nullable=False)  # e.g., 200, 201, 400

    endpoint = relationship("Endpoint", back_populates="test_cases")
    results = relationship("TestResult", back_populates="test_case", cascade="all, delete-orphan")

