"""add stateful scenario tables

Revision ID: 5b86dc9aa102
Revises: db0677f63074
Create Date: 2026-08-27 15:18:38.563305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b86dc9aa102'
down_revision: Union[str, Sequence[str], None] = 'db0677f63074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['specification_id'], ['api_specifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_scenarios_id'), 'test_scenarios', ['id'], unique=False)
    op.create_table('scenario_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('extract_rules', sa.JSON(), nullable=True),
    sa.Column('inject_rules', sa.JSON(), nullable=True),
    sa.Column('expected_status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['test_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_steps_id'), 'scenario_steps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_steps_id'), table_name='scenario_steps')
    op.drop_table('scenario_steps')
    op.drop_index(op.f('ix_test_scenarios_id'), table_name='test_scenarios')
    op.drop_table('test_scenarios')
    # ### end Alembic commands ###
