"""add endpoints table

Revision ID: 6b12429dbd54
Revises: cbb367783f90
Create Date: 2026-07-25 10:38:43.734074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b12429dbd54'
down_revision: Union[str, Sequence[str], None] = 'cbb367783f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specification_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('request_schema', sa.JSON(), nullable=True),
    sa.Column('response_schema', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['specification_id'], ['api_specifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_id'), 'endpoints', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoints_id'), table_name='endpoints')
    op.drop_table('endpoints')
    # ### end Alembic commands ###
