"""add path and query params to test cases

Revision ID: 71d303c080d9
Revises: c87d8f9c1974
Create Date: 2026-08-03 20:08:52.100050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d303c080d9'
down_revision: Union[str, Sequence[str], None] = 'c87d8f9c1974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('path_params', sa.JSON(), nullable=True))
    op.add_column('test_cases', sa.Column('query_params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'query_params')
    op.drop_column('test_cases', 'path_params')
    # ### end Alembic commands ###
