"""unified smart pipeline models

Revision ID: c3503a09f8d6
Revises: 5b86dc9aa102
Create Date: 2026-08-31 14:41:11.558752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3503a09f8d6'
down_revision: Union[str, Sequence[str], None] = '5b86dc9aa102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema while preserving the legacy test-case result table."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    table_names = set(inspector.get_table_names())

    # The legacy test-case implementation already used `test_results`.  Keep
    # those records instead of failing or deleting them when smart pipelines
    # introduce scenario-step results with the same table name.
    if 'test_results' in table_names:
        columns = {column['name'] for column in inspector.get_columns('test_results')}
        if 'scenario_step_id' not in columns:
            if 'legacy_test_results' not in table_names:
                op.rename_table('test_results', 'legacy_test_results')
                op.execute('ALTER INDEX IF EXISTS ix_test_results_id RENAME TO ix_legacy_test_results_id')
            else:
                raise RuntimeError('Cannot migrate test_results: legacy_test_results already exists.')
            table_names.remove('test_results')

    if 'test_results' not in table_names:
        op.create_table('test_results',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('scenario_step_id', sa.Integer(), nullable=False),
        sa.Column('actual_status', sa.Integer(), nullable=True),
        sa.Column('is_passed', sa.Boolean(), nullable=False),
        sa.Column('response_body', sa.JSON(), nullable=True),
        sa.Column('execution_time_ms', sa.Float(), nullable=True),
        sa.Column('error_message', sa.String(), nullable=True),
        sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['scenario_step_id'], ['scenario_steps.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    op.add_column('scenario_steps', sa.Column('step_type', sa.String(), nullable=False))
    op.add_column('scenario_steps', sa.Column('category', sa.String(), nullable=True))
    op.add_column('scenario_steps', sa.Column('mutates_state', sa.Boolean(), nullable=True))
    op.add_column('scenario_steps', sa.Column('path_params', sa.JSON(), nullable=True))
    op.add_column('scenario_steps', sa.Column('query_params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_steps', 'query_params')
    op.drop_column('scenario_steps', 'path_params')
    op.drop_column('scenario_steps', 'mutates_state')
    op.drop_column('scenario_steps', 'category')
    op.drop_column('scenario_steps', 'step_type')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_table('test_results')
    # ### end Alembic commands ###
