"""unified smart pipeline models

Revision ID: c3503a09f8d6
Revises: 5b86dc9aa102
Create Date: 2026-08-31 14:41:11.558752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3503a09f8d6'
down_revision: Union[str, Sequence[str], None] = '5b86dc9aa102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_step_id', sa.Integer(), nullable=False),
    sa.Column('actual_status', sa.Integer(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=False),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scenario_step_id'], ['scenario_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_id'), 'test_results', ['id'], unique=False)
    op.add_column('scenario_steps', sa.Column('step_type', sa.String(), nullable=False))
    op.add_column('scenario_steps', sa.Column('category', sa.String(), nullable=True))
    op.add_column('scenario_steps', sa.Column('mutates_state', sa.Boolean(), nullable=True))
    op.add_column('scenario_steps', sa.Column('path_params', sa.JSON(), nullable=True))
    op.add_column('scenario_steps', sa.Column('query_params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_steps', 'query_params')
    op.drop_column('scenario_steps', 'path_params')
    op.drop_column('scenario_steps', 'mutates_state')
    op.drop_column('scenario_steps', 'category')
    op.drop_column('scenario_steps', 'step_type')
    op.drop_index(op.f('ix_test_results_id'), table_name='test_results')
    op.drop_table('test_results')
    # ### end Alembic commands ###
