"""add parameters and security to endpoints

Revision ID: c87d8f9c1974
Revises: 30e13927e595
Create Date: 2026-07-30 14:58:20.187923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c87d8f9c1974'
down_revision: Union[str, Sequence[str], None] = '30e13927e595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endpoints', sa.Column('parameters', sa.JSON(), nullable=True))
    op.add_column('endpoints', sa.Column('security', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endpoints', 'security')
    op.drop_column('endpoints', 'parameters')
    # ### end Alembic commands ###
